/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import guiamedico.Clinica;
import guiamedico.Hospital;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Thales
 */
public class ResultadoInstituicao extends javax.swing.JFrame {

    /**
     * Creates new form BuscaInstituicao
     */
    private GuiaMedicoMain janelaPrincipal;
    private List<Hospital> hosp;
    private List<Clinica> clin;

    public ResultadoInstituicao() {
        initComponents();
    }

    public ResultadoInstituicao(GuiaMedicoMain janelaAnterior, List<Hospital> hosp, List<Clinica> clin) {
        this();
        this.janelaPrincipal = janelaAnterior;
        //this.jpIdentifica = jpIdentifica;
        this.hosp = hosp;
        this.clin = clin;

        //System.out.printf("%d", hosp.size());
        //System.out.printf("%d", clin.size());
        DefaultListModel listModel;
        listModel = new DefaultListModel();
        if (clin == null) {
            if (hosp.size() == 0) {
                listModel.addElement("Nenhum item corresponde à sua busca");
                jlResultadoBusca.setModel(listModel);
            } else {
                for (int i = 0; i < hosp.size(); i++) {
                    listModel.addElement(hosp.get(i).getNome());
                    listModel.addElement(hosp.get(i).getEndereco());
                    listModel.addElement(hosp.get(i).getTelefone());
                    listModel.addElement(hosp.get(i).getCidade());
                    listModel.addElement(hosp.get(i).getEmail());
                    listModel.addElement("\n");
                }
                jlResultadoBusca.setModel(listModel);
            }
        } else {
            if (clin.size() == 0) {
                listModel.addElement("Nenhum item corresponde à sua busca");
                jlResultadoBusca.setModel(listModel);
            } else {
                for (int i = 0; i < clin.size(); i++) {
                    listModel.addElement(clin.get(i).getNome());
                    listModel.addElement(clin.get(i).getEndereco());
                    listModel.addElement(clin.get(i).getTelefone());
                    listModel.addElement(clin.get(i).getCidade());
                    listModel.addElement(clin.get(i).getEmail());
                    listModel.addElement("\n");
                }
                jlResultadoBusca.setModel(listModel);
            }
        }

        //listModel.addElement(hosp.get(0).getNome());
        //jlResultadoBusca.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLogoInstituicao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpStatusInstituicao = new javax.swing.JPanel();
        lbStatusInstituicao = new javax.swing.JLabel();
        jpResultadoInstituicao = new javax.swing.JPanel();
        jspResultadoInstituicao = new javax.swing.JScrollPane();
        jlResultadoBusca = new javax.swing.JList();

        jpLogoInstituicao.setBackground(new java.awt.Color(255, 255, 255));
        jpLogoInstituicao.setPreferredSize(new java.awt.Dimension(550, 150));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo Medicina.-800x800.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jpLogoInstituicaoLayout = new javax.swing.GroupLayout(jpLogoInstituicao);
        jpLogoInstituicao.setLayout(jpLogoInstituicaoLayout);
        jpLogoInstituicaoLayout.setHorizontalGroup(
            jpLogoInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoInstituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpLogoInstituicaoLayout.setVerticalGroup(
            jpLogoInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoInstituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jpStatusInstituicao.setBackground(new java.awt.Color(255, 255, 255));
        jpStatusInstituicao.setPreferredSize(new java.awt.Dimension(571, 60));

        lbStatusInstituicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpStatusInstituicaoLayout = new javax.swing.GroupLayout(jpStatusInstituicao);
        jpStatusInstituicao.setLayout(jpStatusInstituicaoLayout);
        jpStatusInstituicaoLayout.setHorizontalGroup(
            jpStatusInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStatusInstituicaoLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(lbStatusInstituicao)
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jpStatusInstituicaoLayout.setVerticalGroup(
            jpStatusInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStatusInstituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbStatusInstituicao)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jpResultadoInstituicao.setBackground(new java.awt.Color(255, 255, 255));

        jlResultadoBusca.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Hospital ou Clínica 1 e dados", "Hospital ou Clínica 2 e dados", "Hospital ou Clínica 3 e dados", "Hospital ou Clínica 4 e dados", "Hospital ou Clínica 5 e dados", "Hospital ou Clínica 6 e dados" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jspResultadoInstituicao.setViewportView(jlResultadoBusca);

        javax.swing.GroupLayout jpResultadoInstituicaoLayout = new javax.swing.GroupLayout(jpResultadoInstituicao);
        jpResultadoInstituicao.setLayout(jpResultadoInstituicaoLayout);
        jpResultadoInstituicaoLayout.setHorizontalGroup(
            jpResultadoInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpResultadoInstituicaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jspResultadoInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jpResultadoInstituicaoLayout.setVerticalGroup(
            jpResultadoInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultadoInstituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspResultadoInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLogoInstituicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(jpResultadoInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 551, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jpStatusInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpLogoInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jpResultadoInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addComponent(jpStatusInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(171, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadoInstituicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jlResultadoBusca;
    private javax.swing.JPanel jpLogoInstituicao;
    private javax.swing.JPanel jpResultadoInstituicao;
    private javax.swing.JPanel jpStatusInstituicao;
    private javax.swing.JScrollPane jspResultadoInstituicao;
    private javax.swing.JLabel lbStatusInstituicao;
    // End of variables declaration//GEN-END:variables
}
